name: alice_dio
description: "Alice + Dio integration. It contains plugin for Alice which allows to use Dio package."
version: 1.0.6
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - interceptor
  - alice

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  alice:
    # path: ../alice
    git:
      url: https://github.com/skeyboy/alice.git
      ref: feat/1.0.0-dev12
      commit: 20e5c4e1c34da301eddbe13ea552d7d68ab5eda3
      path: packages/alice
  dio: ^5.8.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.2
  mocktail: ^1.0.4
  http_mock_adapter: ^0.6.1
  alice_test: ^1.0.0
